### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by rvosa** [flora-phenotype-ontology/flopoontology#1]
Hi Rob,

could you add a small README? I don't really know where to start...

Thanks,

Rutger

**Comment by leechuck** [comment]
> > > > > "RV" == Rutger Vos notifications@github.com writes:

Dear Rutget,

I just got back to UK and will start cleaning up the code from Monday
onwards. A README will be there, too. Sorry for the delay, I know how
hard it is to keep the momentum from the hackathon going, and I will
try my best to clean things up and improve the current code (so that we
will at least get some results from the other floras).

R

```
RV> Hi Rob, could you add a small README? I don't really know where
RV> to start...

RV> Thanks,

RV> Rutger

RV> — Reply to this email directly or view it on GitHub.
```

**Comment by leechuck** [comment]
Can this be closed? The Readme has at least basic documentation now.
